//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalDepartmentDegtyannikovIN3802
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staffs
    {
        public int StaffId { get; set; }
        public string Fam { get; set; }
        public string Name { get; set; }
        public string MiddlleName { get; set; }
        public string NumberPhone { get; set; }
        public string Address { get; set; }
        public System.DateTime DateOfEmployment { get; set; }
        public System.DateTime DateOfBearth { get; set; }
        public string Room { get; set; }
        public string WorkExperience { get; set; }
        public Nullable<int> SexId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> EducationId { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Positions Positions { get; set; }
        public virtual Sexes Sexes { get; set; }
        public virtual Educations Educations { get; set; }
    }
}
